#!/bin/bash
### BEGIN INIT INFO
# Provides:          redmine
# Required-Start:    $local_fs $remote_fs $network
# Required-Stop:     $local_fs $remote_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: redmine webrick
# Description:       redmine webrick server autostart-script
### END INIT INFO

. /lib/lsb/init-functions

# Modify it to your configuration
DIR=/usr/integrated-team-tracker
RUBY=$DIR/.rvm/rubies/ruby-1.8.7-p352/bin/ruby
REDMINE=$DIR/redmine

# Start Redmine in daemon mode.
start(){
	echo -n "Starting Redmine WebRick"
	cd $REDMINE
	echo -n .
	$RUBY script/server -d -e production &> /dev/null
	echo -n .
	log_success_msg 0
}

# Stop Redmine daemon
stop(){
	echo -n  "Stopping Redmine WebRick"
	RUBYPID=`ps aux | grep "$RUBY script/server -d -e production" | grep -v grep | awk '{print $2}'`
	echo -n .
	if [ "x$RUBYPID" != "x" ]; then
		kill -2 $RUBYPID
	fi
	log_success_msg 0
}

# Check if Redmine is running
status(){
	echo "$RUBY script/server -d -e production"
	RUBYPID=`ps aux | grep "$RUBY script/server -d -e production" | grep -v grep | awk '{print $2}'`
	if [ "x$RUBYPID" = "x" ]; then
		echo "* Redmine is not running"
	else
		echo "* Redmine is running"
	fi
}


case "$1" in
	start)
		start
		;;
	
	stop)
		stop
		;;
	
	status)
		status
		;;
	
	restart|force-reload)
		stop
		start
		;;

	*)
		echo "Usage: $0 {start|stop|restart|force-reload|status}"
		exit 1

esac
