<?php

require_once 'src/CommitMessage/Analyse.php';

/**
 * Test class for CommitMessage_Analyse.
 * Generated by PHPUnit on 2011-10-26 at 17:25:50.
 */
class CommitMessage_AnalyseTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var CommitMessage_Analyse
     */
    protected $_object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->_object = new CommitMessage_Analyse;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * test getting and setting of splitter
     */
    public function testGetSetSplitter()
    {
        $splitter = $this->getMock(
            'CommitMessage_Splitter'
        );

        $this->_object->setSplitter($splitter);
        $this->assertSame($splitter, $this->_object->getSplitter());
    }

    /**
     * check for working caller relation in setter
     */
    public function testSetHandlerStack()
    {
        $handlerStack = $this->getMock(
            'CommitMessage_HandlerStack',
            array('setCaller')
        );
        $handlerStack->expects($this->once())
                     ->method('setCaller')
                     ->with($this->isInstanceOf($this->_object));

        $this->_object->setHandlerStack($handlerStack);
    }

    /**
     * test missing splitter
     */
    public function testAnalyseMissingSplitter()
    {
        $this->setExpectedException('Exception');
        $this->_object->analyse();
    }

    /**
     * test missing handler stack
     */
    public function testAnalyseMissingHandlerStack()
    {
        $this->setExpectedException('Exception');
        $this->_object->setSplitter($this->getMock('CommitMessage_Splitter'));
        $this->_object->analyse();
    }
    /**
     * check for missing head error
     */
    public function testAnalyseMissingHead()
    {
        $splitter = $this->getMock(
            'CommitMessage_Splitter',
            array(
                'getData'
            )
        );
        $splitter->expects($this->once())
                 ->method('getData')
                 ->will($this->returnValue(array('head'=>'', 'body'=>'body')));

        $handlerStack = $this->getMock(
            'CommitMessage_HandlerStack',
            array(
                'setCaller',
                'append'
            )
        );
        $handlerStack->expects($this->once())
                     ->method('append')
                     ->with($this->isInstanceOf('CommitMessage_Handler_WarnMissingText'));
    
        $this->_object->setSplitter($splitter);
        $this->_object->setHandlerStack($handlerStack);

        $this->_object->analyse();
    }

    public function testAnalyseMissingBody()
    {
        $splitter = $this->getMock(
            'CommitMessage_Splitter',
            array(
                'getData'
            )
        );
        $splitter->expects($this->once())
                 ->method('getData')
                 ->will($this->returnValue(array('head'=>'head', 'body'=>'')));

        $handlerStack = $this->getMock(
            'CommitMessage_HandlerStack',
            array(
                'setCaller',
                'append'
            )
        );
        $handlerStack->expects($this->once())
                     ->method('append')
                     ->with($this->isInstanceOf('CommitMessage_Handler_WarnMissingText'));
    
        $this->_object->setSplitter($splitter);
        $this->_object->setHandlerStack($handlerStack);

        $this->_object->analyse();
    }
}
