<?php

require_once 'src/CommitMessage/Analyse.php';

/**
 * Test class for CommitMessage_Analyse.
 * Generated by PHPUnit on 2011-10-26 at 17:25:50.
 */
class CommitMessage_AnalyseTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var CommitMessage_Analyse
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new CommitMessage_Analyse;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testSetSplitter().
     */
    public function testSetSplitter()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetSplitter().
     */
    public function testGetSplitter()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSetHandlerStack().
     */
    public function testSetHandlerStack()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testAnalyse().
     */
    public function testAnalyse()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
?>
