<?php

require_once 'src/CommitMessage/HandlerStack.php';

/**
 * Test class for CommitMessage_HandlerStack.
 * Generated by PHPUnit on 2011-10-26 at 21:18:48.
 */
class CommitMessage_HandlerStackTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var CommitMessage_HandlerStack
     */
    protected $_object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->_object = new CommitMessage_HandlerStack;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * test getting and setting caller as well as not allowing to override
     */
    public function testGetSetCaller()
    {
        $caller = new stdClass;
        $this->_object->setCaller($caller);
        $this->assertSame($caller, $this->_object->getCaller());

        $this->setExpectedException('Exception');
        $this->_object->setCaller($caller);
    }

    /**
     */
    public function testAppend()
    {
        $data = $this->getMock('stdClass', array('setCaller'));
        $data->expects($this->once())
             ->method('setCaller')
             ->with($this->isInstanceOf($this->_object));

        $this->_object->append($data);
    }

    /**
     */
    public function testRun()
    {
        $handler = $this->getMock(
            'stdClass',
            array(
                'setCaller',
                'run'
            )
        );
        $handler->expects($this->once())
                ->method('setCaller')
                ->with($this->isInstanceOf($this->_object));
        $handler->expects($this->once())
                ->method('run');

        $this->_object->append($handler);
        $this->_object->run();
    }

}
