<?php

require_once 'src/CommitMessage/Handler/Issue.php';

class Concrete_CommitMessage_Handler_Issue
    extends CommitMessage_Handler_Issue
{
    /**
     */
    public function run()
    {
    }
    /**
     * expose protected
     */
    public function setRedmine($redmine)
    {
        return $this->_setRedmine($redmine);
    }
    public function getRedmine()
    {
        return $this->_getRedmine();
    }
}

/**
 * Test class for CommitMessage_Handler_Issue.
 * Generated by PHPUnit on 2011-10-26 at 21:53:10.
 */
class CommitMessage_Handler_IssueTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var CommitMessage_Handler_Issue
     */
    protected $_object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->_object = new Concrete_CommitMessage_Handler_Issue;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     */
    public function testGetSetIssueId()
    {
        $issueId = 1234;
        
        $this->_object->setIssueId($issueId);
        $this->assertEquals($issueId, $this->_object->getIssueId($issueId));
    }

    /**
     */
    public function testGetSetRedmine()
    {
        $factory = $this->getMock(
            'CommitMessage_Factory',
            array(
                'create'
            )
        );
        $redmine = $this->getMock('Issue');
        $this->_object->setRedmine($redmine);
        $this->assertEquals($redmine, $this->_object->getRedmine());
    }

    public function testGetSetFactory()
    {
        $factory = $this->getMock('CommitMessage_Factory');

        $this->_object->setFactory($factory);

        $this->assertEquals($factory, $this->_object->getFactory());
    }
}
