<?php

require_once 'src/CommitMessage/Handler/Issue.php';

/**
 * Test class for CommitMessage_Handler_Issue.
 * Generated by PHPUnit on 2011-10-26 at 21:53:10.
 */
class CommitMessage_Handler_IssueTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var CommitMessage_Handler_Issue
     */
    protected $_object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->_object = new CommitMessage_Handler_Issue;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testSetIssueId().
     */
    public function testSetIssueId()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetIssueId().
     */
    public function testGetIssueId()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
