<?php

require_once 'src/CommitMessage/Handler/IssueCheck.php';

/**
 * Test class for CommitMessage_Handler_IssueCheck.
 * Generated by PHPUnit on 2011-10-26 at 21:56:59.
 */
class CommitMessage_Handler_IssueCheckTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var CommitMessage_Handler_IssueCheck
     */
    protected $_object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->_object = new CommitMessage_Handler_IssueCheck;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testRun().
     */
    public function testRun()
    {
        $factory = $this->getMock(
            'CommitMessage_Factory',
            array (
                'create'
            )
        );
        $issue = $this->getMock(
            'Issue',
            array(
                'find'
            )
        );
        $factory->expects($this->any())
                ->method('create')
                ->with('Issue')
                ->will($this->returnValue($issue));

        $this->_object->setFactory($factory);
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
        $this->_object->run();
    }
}
