<?php

require_once 'src/CommitMessage/Handler/IssueChangeStatus.php';

/**
 * Test class for CommitMessage_Handler_IssueChangeStatus.
 * Generated by PHPUnit on 2011-10-27 at 11:50:03.
 */
class CommitMessage_Handler_IssueChangeStatusTest 
    extends PHPUnit_Framework_TestCase
{
    /**
     * @var CommitMessage_Handler_IssueChangeStatus
     */
    protected $_object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->_object = new CommitMessage_Handler_IssueChangeStatus;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testSetNewStatus().
     */
    public function testSetNewStatus()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testRun().
     */
    public function testRun()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
